---
# tasks file for /etc/ansible/roles/install-lamp
- name: Installation du service "Apache2"
  ansible.builtin.apt:
    name: apache2
    state: present
  become: yes

- name: Installation du service "MariaDB"
  ansible.builtin.apt:
    name: mariadb-server
    state: present
  become: yes

- name: Installation des services "PHP"
  ansible.builtin.apt:
    name:
      - php
      - php-mysql
      - php-mbstring
      - php-curl
      - php-gd
      - php-xml
      - php-intl
      - php-ldap
      - php-apcu
      - php-xmlrpc
      - php-zip
      - php-bz2
      - php-imap
    state: present
  become: yes